export const CITIES = [
  { id: 1, name: "Cairo" },
  { id: 2, name: "Alexandria" },
  { id: 3, name: "Giza" },
  { id: 4, name: "Shubra El-Kheima" },
  { id: 5, name: "Port Said" },
  { id: 6, name: "Suez" },
  { id: 7, name: "Luxor" },
  { id: 8, name: "Aswan" },
  { id: 9, name: "Tanta" },
  { id: 10, name: "Ismailia" },
  { id: 11, name: "Faiyum" },
  { id: 12, name: "Zagazig" },
  { id: 13, name: "Damietta" },
  { id: 14, name: "Asyut" },
  { id: 15, name: "Minya" },
  { id: 16, name: "Damanhur" },
  { id: 17, name: "Beni Suef" },
  { id: 18, name: "Hurghada" },
  { id: 19, name: "Qena" },
  { id: 20, name: "Sohag" },
];
